name: quality checks

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
        paths:
            - ./**.ts
            - package.json
            - tsconfig.json
            - .github/workflows/**.yml

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: canary

            - name: install
              run: bun install

            - name: typecheck
              run: bun run typecheck

            - name: test
              run: bun test

    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: |
                  bun install
                  bun run fmt:check
